### ISSUE TITLE
Issue with nextjs since v0.3.7

### ISSUE THREAD

**Issue by Le0Developer** [hCaptcha/react-hcaptcha#124]
I tried using @hcaptcha/react-hcaptcha with nextjs but the latest version that is working is 0.3.7.

Since 0.3.7 I am always getting the following error:
```
wait  - compiling / (client and server)...
error - ./node_modules/@hcaptcha/react-hcaptcha/dist/index.js:3:0
Module not found: Can't resolve '@babel/runtime/helpers/interopRequireDefault'

Import trace for requested module:
./pages/index.tsx

https://nextjs.org/docs/messages/module-not-found
wait  - compiling /_error (client and server)...
error - ./node_modules/@hcaptcha/react-hcaptcha/dist/index.js:3:0
Module not found: Can't resolve '@babel/runtime/helpers/interopRequireDefault'

Import trace for requested module:
./pages/index.tsx

https://nextjs.org/docs/messages/module-not-found
error - Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /hcaptcha-repro/node_modules/@hcaptcha/react-hcaptcha/dist/index.js
- /hcaptcha-repro/.next/server/pages/index.js
- /hcaptcha-repro/node_modules/next/dist/server/require.js
- /hcaptcha-repro/node_modules/next/dist/server/load-components.js
- /hcaptcha-repro/node_modules/next/dist/build/utils.js
- /hcaptcha-repro/node_modules/next/dist/build/output/store.js
- /hcaptcha-repro/node_modules/next/dist/build/output/index.js
- /hcaptcha-repro/node_modules/next/dist/cli/next-dev.js
- /hcaptcha-repro/node_modules/next/dist/bin/next
```

Reproduction repository: https://github.com/Le0Developer/hcaptcha-repro

Commands to run: `npm run dev` (dev server) or `npm run build` (build static files)

**Comment by zoryana94** [comment]
Hi @Le0Developer!

Thank you for pointing out this issue!
It's been fixed in our [latest release 1.3.0, please check it out for more details!](https://github.com/hCaptcha/react-hcaptcha/releases/tag/1.3.0)
I've tested it in [your repo](https://github.com/Le0Developer/hcaptcha-repro) and I cannot reproduce the bug anymore.
Please check and let me know if everything is as expected.

Please do not hesitate to contact us! We are open to feedback and aim at creating the best possible experience while using our products!

Best Regards,
IMI Dev Team

**Comment by Le0Developer** [comment]
Thank you, it's working with v1.3.0!
